
import feedparser
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from datetime import datetime, timedelta
import hashlib
import os
import logging
import random
import schedule
import time

from googletrans import Translator
from pywhatkit import sendwhatmsg_instantly

# ---------------------------
# SECTION 1 : CONFIGURATION
# ---------------------------

# Adresse email expéditeur
from_email = "mzo.fpa@gmail.com"
password = "jevt qvas vrpj bveo"

# Liste des destinataires
to_emails = [
    "muzioolivi.fabien@hotmail.fr", "flo.dupasquier@laposte.net", "luclamour30@gmail.com", "loic.gabaud@gmail.com", "jc.deschouwer@gmail.com", 
    "vincenttoureille@gmail.com", "stephane.foucrier@gendarmerie.interieur.gouv.fr", "p.ceccaldi1971@gmail.com", "denisterribile@gmail.com"


]

# Liste des numéros WhatsApp
whatsapp_numbers = [
    "+33662890361", "+33665524828", "+33673399180", "+33610893121", "+33612779825"
]

# Chemin du logo pour les emails
logo_path = "C:/Users/muzio/OneDrive/Bureau/projet appli/source/logo/python/Fast-port-assess-blanc.png"

# Fichier des liens archivés
archive_file = r"C:\Users\muzio\OneDrive\Bureau\code\articles_surveillance.txt"

# Durée maximale des articles en jours
MAX_ARTICLE_AGE_DAYS = 3

# Mots-clés par langue
keywords_by_language = {
    'fr': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE', 
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', 'sécurité maritime',
        'sécurité portuaire', 'terrorisme', 'piraterie', 'trafic de drogue',
        'vol de marchandises', 'mouvements dockers', 'EEI/incendie volontaire',
        'marchandises dangereuses', 'prises d\'otages', 'racket', 'vols matériels',
        'clandestins', 'pollution maritime', 'espionnage industriel', 'ingérence',
        'accord maritime', 'mouvement de matériel militaire', 'sécurité numérique',
        'cyberattaque', 'AFCC', 'BBL CARGO', 'BOLLORE LOGISTICS',
        'BUREAU DE TRANSIT MARSEILLAIS', 'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT',
        'C.STEINWEG', 'CENTRIMEX', 'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN',
        'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL', 'COTRASUD', 'CT LOG',
        'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL', 'DIMOTRANS', 'DSV',
        'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP', 'FAVAT BY CLASQUIN',
        'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS', 'GEODIS',
        'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED', 'HBI',
        'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS', 'MÉDITERRANÉE MANUTENTION',
        'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)', 'LAFARGE',
        'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)', 'NAPOLI DRY DOCKS',
        'FOS DOCKS SERVICES', 'COSTA SHIPYARD', 'GENOA SEA MAINTENANCE',
        'NAVAL GROUP', 'PALUMBO SHIPYARD', 'DAMEN SHIPREPAIR & CONVERSION',
        'LNG TERMINAL FOS', 'TOTAL ENERGIES', 'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA',
        'PETROINEOS', 'VOPAK TERMINAL', 'AXENS INDUSTRY', 'IFPEN',
        'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'Taxe sur le tonnage'
    ],
     'en': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', 'maritime security',
        'port security', 'terrorism', 'piracy', 'drug trafficking', 'cargo theft',
        'dock movements', 'IED/voluntary fire', 'dangerous goods', 'hostage-taking',
        'ransom', 'theft of materials', 'stowaways', 'maritime pollution',
        'industrial espionage', 'interference', 'military equipment movement',
        'Cyberattack', 'Digital Security', 'AFCC', 'BBL CARGO', 'BOLLORE LOGISTICS',
        'BUREAU DE TRANSIT MARSEILLAIS', 'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT',
        'C.STEINWEG', 'CENTRIMEX', 'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN',
        'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL', 'COTRASUD', 'CT LOG',
        'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL', 'DIMOTRANS', 'DSV',
        'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP', 'FAVAT BY CLASQUIN',
        'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS', 'GEODIS',
        'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED', 'HBI',
        'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS', 'MÉDITERRANÉE MANUTENTION',
        'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)', 'LAFARGE',
        'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)', 'NAPOLI DRY DOCKS',
        'FOS DOCKS SERVICES', 'COSTA SHIPYARD', 'GENOA SEA MAINTENANCE',
        'NAVAL GROUP', 'PALUMBO SHIPYARD', 'DAMEN SHIPREPAIR & CONVERSION',
        'LNG TERMINAL FOS', 'TOTAL ENERGIES', 'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA',
        'PETROINEOS', 'VOPAK TERMINAL', 'AXENS INDUSTRY', 'IFPEN',
        'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'Tonnage Tax'
    ],
    'es': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', 'seguridad marítima',
        'seguridad portuaria', 'terrorismo', 'piratería', 'tráfico de drogas',
        'robo de carga', 'movimientos de estibadores', 'artefacto explosivo improvisado',
        'mercancías peligrosas', 'toma de rehenes', 'rescate', 'Ciberataque',
        'Seguridad digital', 'AFCC', 'BBL CARGO', 'BOLLORE LOGISTICS',
        'BUREAU DE TRANSIT MARSEILLAIS', 'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT',
        'C.STEINWEG', 'CENTRIMEX', 'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN',
        'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL', 'COTRASUD', 'CT LOG',
        'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL', 'DIMOTRANS', 'DSV',
        'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP', 'FAVAT BY CLASQUIN',
        'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS', 'GEODIS',
        'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED', 'HBI',
        'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'SEAYARD TERMINAL', 'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS',
        'MÉDITERRANÉE MANUTENTION', 'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)',
        'LAFARGE', 'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)',
        'NAPOLI DRY DOCKS', 'FOS DOCKS SERVICES', 'COSTA SHIPYARD',
        'GENOA SEA MAINTENANCE', 'NAVAL GROUP', 'PALUMBO SHIPYARD',
        'DAMEN SHIPREPAIR & CONVERSION', 'LNG TERMINAL FOS', 'TOTAL ENERGIES',
        'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA', 'PETROINEOS', 'VOPAK TERMINAL',
        'AXENS INDUSTRY', 'IFPEN', 'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'Impuesto sobre el tonelaje'
    ],
   'it': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', 'sicurezza marittima',
        'sicurezza portuale', 'terrorismo', 'pirateria', 'traffico di droga',
        'furto di merci', 'movimenti dei portuali', 'IED/incendio doloso',
        'merci pericolose', 'presa di ostaggi', 'riscatto', 'Attacco informatico',
        'Sicurezza digitale', 'AFCC', 'BBL CARGO', 'BOLLORE LOGISTICS',
        'BUREAU DE TRANSIT MARSEILLAIS', 'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT',
        'C.STEINWEG', 'CENTRIMEX', 'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN',
        'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL', 'COTRASUD', 'CT LOG',
        'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL', 'DIMOTRANS', 'DSV',
        'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP', 'FAVAT BY CLASQUIN',
        'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS', 'GEODIS',
        'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED', 'HBI',
        'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'SEAYARD TERMINAL', 'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS',
        'MÉDITERRANÉE MANUTENTION', 'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)',
        'LAFARGE', 'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)',
        'NAPOLI DRY DOCKS', 'FOS DOCKS SERVICES', 'COSTA SHIPYARD',
        'GENOA SEA MAINTENANCE', 'NAVAL GROUP', 'PALUMBO SHIPYARD',
        'DAMEN SHIPREPAIR & CONVERSION', 'LNG TERMINAL FOS', 'TOTAL ENERGIES',
        'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA', 'PETROINEOS', 'VOPAK TERMINAL',
        'AXENS INDUSTRY', 'IFPEN', 'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'Tassa sul tonnellaggio'
    ],
    'pt': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', 'segurança marítima',
        'segurança portuária', 'terrorismo', 'pirataria', 'tráfico de drogas',
        'roubo de carga', 'movimentos portuários', 'IED/incêndio voluntário',
        'mercadorias perigosas', 'sequestro', 'Ciberataque', 'Segurança digital',
        'AFCC', 'BBL CARGO', 'BOLLORE LOGISTICS', 'BUREAU DE TRANSIT MARSEILLAIS',
        'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT', 'C.STEINWEG', 'CENTRIMEX',
        'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN', 'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL',
        'COTRASUD', 'CT LOG', 'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL',
        'DIMOTRANS', 'DSV', 'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP',
        'FAVAT BY CLASQUIN', 'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS',
        'GEODIS', 'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED',
        'HBI', 'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'SEAYARD TERMINAL', 'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS',
        'MÉDITERRANÉE MANUTENTION', 'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)',
        'LAFARGE', 'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)',
        'NAPOLI DRY DOCKS', 'FOS DOCKS SERVICES', 'COSTA SHIPYARD',
        'GENOA SEA MAINTENANCE', 'NAVAL GROUP', 'PALUMBO SHIPYARD',
        'DAMEN SHIPREPAIR & CONVERSION', 'LNG TERMINAL FOS', 'TOTAL ENERGIES',
        'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA', 'PETROINEOS', 'VOPAK TERMINAL',
        'AXENS INDUSTRY', 'IFPEN', 'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'Imposto sobre o tonelagem'
    ],
    'de': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', 'maritime Sicherheit',
        'Hafensicherheit', 'Terrorismus', 'Piraterie', 'Drogenhandel',
        'Fracht Diebstahl', 'Dockbewegungen', 'Sprengsatz', 'Gefährliche Güter',
        'Geiselnahme', 'Cyberangriff', 'Digitale Sicherheit', 'AFCC', 'BBL CARGO',
        'BOLLORE LOGISTICS', 'BUREAU DE TRANSIT MARSEILLAIS',
        'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT', 'C.STEINWEG', 'CENTRIMEX',
        'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN', 'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL',
        'COTRASUD', 'CT LOG', 'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL',
        'DIMOTRANS', 'DSV', 'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP',
        'FAVAT BY CLASQUIN', 'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS',
        'GEODIS', 'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED',
        'HBI', 'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'SEAYARD TERMINAL', 'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS',
        'MÉDITERRANÉE MANUTENTION', 'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)',
        'LAFARGE', 'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)',
        'NAPOLI DRY DOCKS', 'FOS DOCKS SERVICES', 'COSTA SHIPYARD',
        'GENOA SEA MAINTENANCE', 'NAVAL GROUP', 'PALUMBO SHIPYARD',
        'DAMEN SHIPREPAIR & CONVERSION', 'LNG TERMINAL FOS', 'TOTAL ENERGIES',
        'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA', 'PETROINEOS', 'VOPAK TERMINAL',
        'AXENS INDUSTRY', 'IFPEN', 'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'Tonnagesteuer'
    ],
     'nl': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', 'maritieme veiligheid',
        'havenveiligheid', 'terrorisme', 'piraterij', 'drugshandel', 'ladingdiefstal',
        'dokbewegingen', 'gevaarlijke goederen', 'gijzeling', 'losgeld', 'Cyberaanval',
        'Digitale veiligheid', 'AFCC', 'BBL CARGO', 'BOLLORE LOGISTICS',
        'BUREAU DE TRANSIT MARSEILLAIS', 'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT',
        'C.STEINWEG', 'CENTRIMEX', 'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN',
        'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL', 'COTRASUD', 'CT LOG',
        'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL', 'DIMOTRANS', 'DSV',
        'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP', 'FAVAT BY CLASQUIN',
        'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS', 'GEODIS',
        'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED', 'HBI',
        'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'SEAYARD TERMINAL', 'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS',
        'MÉDITERRANÉE MANUTENTION', 'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)',
        'LAFARGE', 'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)',
        'NAPOLI DRY DOCKS', 'FOS DOCKS SERVICES', 'COSTA SHIPYARD',
        'GENOA SEA MAINTENANCE', 'NAVAL GROUP', 'PALUMBO SHIPYARD',
        'DAMEN SHIPREPAIR & CONVERSION', 'LNG TERMINAL FOS', 'TOTAL ENERGIES',
        'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA', 'PETROINEOS', 'VOPAK TERMINAL',
        'AXENS INDUSTRY', 'IFPEN', 'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'Tonnagebelasting'
    ],
   'zh': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', '海运安全', '港口安全',
        '恐怖主义', '海盗', '毒品走私', '货物盗窃', '简易爆炸装置', '危险货物', '人质劫持', '赎金',
        '网络攻击', '数字安全', 'AFCC', 'BBL CARGO', 'BOLLORE LOGISTICS',
        'BUREAU DE TRANSIT MARSEILLAIS', 'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT',
        'C.STEINWEG', 'CENTRIMEX', 'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN',
        'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL', 'COTRASUD', 'CT LOG',
        'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL', 'DIMOTRANS', 'DSV',
        'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP', 'FAVAT BY CLASQUIN',
        'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS', 'GEODIS',
        'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED', 'HBI',
        'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'SEAYARD TERMINAL', 'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS',
        'MÉDITERRANÉE MANUTENTION', 'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)',
        'LAFARGE', 'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)',
        'NAPOLI DRY DOCKS', 'FOS DOCKS SERVICES', 'COSTA SHIPYARD',
        'GENOA SEA MAINTENANCE', 'NAVAL GROUP', 'PALUMBO SHIPYARD',
        'DAMEN SHIPREPAIR & CONVERSION', 'LNG TERMINAL FOS', 'TOTAL ENERGIES',
        'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA', 'PETROINEOS', 'VOPAK TERMINAL',
        'AXENS INDUSTRY', 'IFPEN', 'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', '吨位税'
    ],
   'ja': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', '海上の安全',
        '港の安全', 'テロリズム', '海賊行為', '麻薬取引', '貨物窃盗', '危険物', '人質',
        '身代金', 'サイバー攻撃', 'デジタルセキュリティ', 'AFCC', 'BBL CARGO',
        'BOLLORE LOGISTICS', 'BUREAU DE TRANSIT MARSEILLAIS',
        'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT', 'C.STEINWEG', 'CENTRIMEX',
        'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN', 'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL',
        'COTRASUD', 'CT LOG', 'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL',
        'DIMOTRANS', 'DSV', 'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP',
        'FAVAT BY CLASQUIN', 'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS',
        'GEODIS', 'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED',
        'HBI', 'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'SEAYARD TERMINAL', 'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS',
        'MÉDITERRANÉE MANUTENTION', 'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)',
        'LAFARGE', 'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)',
        'NAPOLI DRY DOCKS', 'FOS DOCKS SERVICES', 'COSTA SHIPYARD',
        'GENOA SEA MAINTENANCE', 'NAVAL GROUP', 'PALUMBO SHIPYARD',
        'DAMEN SHIPREPAIR & CONVERSION', 'LNG TERMINAL FOS', 'TOTAL ENERGIES',
        'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA', 'PETROINEOS', 'VOPAK TERMINAL',
        'AXENS INDUSTRY', 'IFPEN', 'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'トン数税'
    ],
    'ar': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', 'أمن بحري',
        'أمن الموانئ', 'الإرهاب', 'القرصنة', 'تهريب المخدرات', 'سرقة البضائع',
        'البضائع الخطرة', 'احتجاز الرهائن', 'فدية', 'الهجوم السيبراني',
        'الأمن الرقمي', 'AFCC', 'BBL CARGO', 'BOLLORE LOGISTICS',
        'BUREAU DE TRANSIT MARSEILLAIS', 'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT',
        'C.STEINWEG', 'CENTRIMEX', 'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN',
        'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL', 'COTRASUD', 'CT LOG',
        'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL', 'DIMOTRANS', 'DSV',
        'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP', 'FAVAT BY CLASQUIN',
        'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS', 'GEODIS',
        'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED', 'HBI',
        'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'SEAYARD TERMINAL', 'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS',
        'MÉDITERRANÉE MANUTENTION', 'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)',
        'LAFARGE', 'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)',
        'NAPOLI DRY DOCKS', 'FOS DOCKS SERVICES', 'COSTA SHIPYARD',
        'GENOA SEA MAINTENANCE', 'NAVAL GROUP', 'PALUMBO SHIPYARD',
        'DAMEN SHIPREPAIR & CONVERSION', 'LNG TERMINAL FOS', 'TOTAL ENERGIES',
        'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA', 'PETROINEOS', 'VOPAK TERMINAL',
        'AXENS INDUSTRY', 'IFPEN', 'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'ضريبة الحمولة '
    ],
    'he': [
        'CMA CGM', 'MSC', 'HAPAG-LLOYD', 'MAERSK', 'COSCO SHIPPING', 'EVERGREEN',
        'ONE (OCEAN NETWORK EXPRESS)', 'ZIM INTEGRATED SHIPPING SERVICES', 'ARKAS LINE',
        'SEAGO LINE', 'CORSICA LINEA', 'LA MÉRIDIONALE', 'ALGÉRIE FERRIES',
        'CTN (COMPAGNIE TUNISIENNE DE NAVIGATION)', 'CARNIVAL CRUISE LINE',
        'PRINCESS CRUISES', 'HOLLAND AMERICA LINE', 'SEABOURN', 'COSTA CRUISES',
        'AIDA CRUISES', 'CUNARD LINE', 'P&O CRUISES', 'ROYAL CARIBBEAN INTERNATIONAL',
        'CELEBRITY CRUISES', 'SILVERSEA CRUISES', 'TUI CRUISES', 'HAPAG-LLOYD CRUISES',
        'NORWEGIAN CRUISE LINE', 'OCEANIA CRUISES', 'REGENT SEVEN SEAS CRUISES',
        'MSC CRUISES', 'DISNEY CRUISE LINE', 'VIKING CRUISES', 'DREAM CRUISES',
        'STAR CRUISES', 'CRYSTAL CRUISES', 'PONANT', 'HURTIGRUTEN', 'AZAMARA',
        'VIRGIN VOYAGES', 'SETE PORT', 'MARSEILLE-FOS', 'GPMM', 'ביטחון ימי',
        'ביטחון נמל', 'טרור', 'פיראטיות', 'הברחת סמים', 'גניבת מטענים',
        'סחורות מסוכנות', 'לקיחת בני ערובה', 'כופר', 'מתקפת סייבר',
        'אבטחה דיגיטלית', 'AFCC', 'BBL CARGO', 'BOLLORE LOGISTICS',
        'BUREAU DE TRANSIT MARSEILLAIS', 'C.A.T - COMPAGNIE D\'AFFRÈTEMENT ET DE TRANSPORT',
        'C.STEINWEG', 'CENTRIMEX', 'CEVA LOGISTICS', 'CIACAM', 'CLASQUIN',
        'CLI TRANSIT - COMPAGNIE LEBRUN INTERNATIONAL', 'COTRASUD', 'CT LOG',
        'DALIA AGENCE DOUANES SERVICES', 'DB SCHENKER', 'DHL', 'DIMOTRANS', 'DSV',
        'ECU WORLDWIDE FRANCE', 'EUROFRET', 'FAUVEDER GROUP', 'FAVAT BY CLASQUIN',
        'FERON DE CLEBSATTEL', 'FLYTRANS', 'FMI GROUPE', 'GCA LOGISTICS', 'GEODIS',
        'GLOBTRANS', 'GONDRAND SFT', 'INTERLOCUTEUR SUD GPM LOGISTIQUE MED', 'HBI',
        'HEPPNER', 'HERPORT', 'IFB INTERNATIONAL', 'IFS NEUTRAL MARITIME FRANCE NVOCC',
        'INTELOG', 'INTERCARGO S.A.', 'ISMER SA', 'ITP / ITPL', 'KUEHNE+NAGEL',
        'LA GÉNÉRALE DE TRANSIT', 'LAM LOGISTIQUE ET TRANSIT MARTIN', 'LPO SOGENA',
        'M2C LOGISTIQUE ARTIZANORD', 'MANUPORT LOGISTICS', 'MATHEZ FREIGHT',
        'MD SIGRIST LOGISTICS', 'MEDIACO VRAC', 'MÉDITERRANÉE TRANSIT INTERNATIONAL',
        'MILITZER & MÜNCH', 'N.A.T.T - NOUVELLE AGENCE TRANSPORT TRANSIT',
        'NAVI-TRADE FORWARDERS', 'NNR GLOBAL LOGISTICS FRANCE',
        'PENTAGON FREIGHT SERVICES', 'PHILCO INTERNATIONAL', 'PRIMEVER INTERNATIONAL',
        'PROLINAIR', 'PROLOG', 'PROVENCE SERVICES TRADING & MOVING', 'PSA BDP',
        'QUALITAIR & SEA', 'R SEA TRANSIT', 'RHODANIENNE DE TRANSIT',
        'SBT - SEA BER TRANSIT', 'SEAFRIGO', 'SEALOGIS FREIGHT FORWARDING', 'SEATRANS',
        'SEDIS LOGISTICS FRANCE', 'SETCARGO', 'SIFA MARITIME', 'SOMATRANS',
        'SSC CONSOLIDATION', 'T.F.S FRANCE', 'TECHNOTRANS', 'TEPMARE', 'TOURNEBIZE',
        'TRADE MED', 'TRANSCARGO', 'TRANSCAUSSE', 'TRANSISUD', 'TRANSITFRUITS',
        'TRANSPORT ET TRANSIT MARITIME 2TM', 'ULIX GRAND SUD', 'VECTORYS', 'WECARE',
        'XPO LOGISTICS', 'ZIEGLER', 'INTRAMAR', 'PORTSYNERGY',
        'TERMINAL DE CONTENEURS DE FOS (TCF)', 'SEAYARD', 'EUROFOS', 'MEDLOG',
        'MARSEILLE MANUTENTION (MANUMAR)', 'SOMARSAL', 'SOCOMAN', 'MASE',
        'CMA TERMINALS', 'NAT TERMINALS', 'TRADEMAR', 'GEODIS', 'LOGISTIQUE FOS',
        'SEAYARD TERMINAL', 'STEINWEG CONSOLIDATION', 'SOMITIM', 'NAVITRANS',
        'MÉDITERRANÉE MANUTENTION', 'HAROPA LOGISTICS', 'CNR (COMPAGNIE NATIONALE DU RHÔNE)',
        'LAFARGE', 'GRTGAZ TERMINAL', 'CHANTIERS NAVALS DE MARSEILLE (CNM)',
        'NAPOLI DRY DOCKS', 'FOS DOCKS SERVICES', 'COSTA SHIPYARD',
        'GENOA SEA MAINTENANCE', 'NAVAL GROUP', 'PALUMBO SHIPYARD',
        'DAMEN SHIPREPAIR & CONVERSION', 'LNG TERMINAL FOS', 'TOTAL ENERGIES',
        'LAFARGEHOLCIM', 'AIR LIQUIDE', 'ARKEMA', 'PETROINEOS', 'VOPAK TERMINAL',
        'AXENS INDUSTRY', 'IFPEN', 'COMPAGNIE MARITIME DE REPARATION (CMR)', 'SOCARENAM',
        'NAVAL REPAIR SERVICE (NRS)', 'NAUTA DESIGN SERVICES', 'CIRM SERVICES MARSEILLE', 'מס טונה'
    ]
}

# Flux RSS par langue
rss_feeds = {
    'fr': [
        'https://www.france24.com/fr/rss',
        'https://www.lemonde.fr/rss/une.xml',
        'https://www.laprovence.com/rss',
        'https://www.ouest-france.fr/rss/lemarin/lemarin',
	'https://jeunemarine.fr/feed/',
	'https://www.actu-transport-logistique.fr/journal-de-la-marine-marchande/',
        'http://www.journalmarinemarchande.eu/rss.xml',
	'https://www.ouest-france.fr/rss/lemarin/lemarin',
        'https://lemarin.ouest-france.fr/rss',
        'https://www.humanite.fr/mot-cle/nations-unies/feed',
        'https://news.un.org/feed/subscribe/fr/news/topic/economic-development/feed/rss.xml',
        'https://news.un.org/feed/subscribe/fr/news/region/europe/feed/rss.xml',
        'https://www.ouest-france.fr/rss/france',
        'https://news.google.com/rss/search?tbm=nws&q=ouest-france+corse&oq=ouest-france+corse&scoring=n&hl=fr&gl=FR&ceid=FR:fr',
        'https://www.ouest-france.fr/rss/une',
        'https://www.20minutes.fr/feeds/rss-marseille.xml',
        'https://www.marseille.fr/actualites/rss/',
        'https://ulcgtcentremarseille.reference-syndicale.fr/feed/',
        'https://www.marseille.aeroport.fr/alerte-rss',
        'https://www.lemonde.fr/marseille/rss_full.xml',
        'https://www.varmatin.com/ville/toulon/rss',
        'https://www.lemonde.fr/oceans/rss_full.xml',
        'https://www.letelegramme.fr/economie/mer/rss.xml',
        'https://kill-the-newsletter.com/feeds/gp91zd3jg04na7zd9fpu.xml',
        'https://bastia-port.cci.corsica/feed/',
        'https://www.premar-atlantique.gouv.fr/avis/rss/AVURNAV?format=rss',
        'https://sosmediterranee.fr/feed/',
        'https://www.france-cyber-maritime.eu/fr/feed/',
        'https://ilerousse-port.cci.corsica/feed/',
        'https://www.cluster-maritime.fr/feed/',
        'https://portsetcorridors.com/feed/',
        'https://ec.europa.eu/commission/presscorner/api/rss?language=fr&documenttype=&policyarea=39&commissioner=&pagesize=10',
        'https://www.lemonde.fr/otan/rss_full.xml',
        'https://www.letelegramme.fr/monde/guerre-ukraine-russie/rss.xml',
        'https://ihedn.fr/feed/',
        'http://mars-attaque.blogspot.com/feeds/posts/default?alt=rss',
        'https://www.opex360.com/feed/',
        'https://www.francetvinfo.fr/economie/syndicats.rss',
        'http://feeds.feedburner.com/Cfdtfr',
        'https://santesocial.cfecgc.org/feed/',
        'https://www.cftc.fr/feed',
        'https://medias-cgc.blogspot.com/feeds/posts/default',
        'https://www.cgt.fr/rss.xml',
        'https://www.cgtetat.fr/spip.php?page=backend',
        'https://www.cgt59.fr/feed/',
        'http://ouvalacgt.over-blog.com/rss',
        'https://ulcgtcentremarseille.reference-syndicale.fr/feed/',
        'https://www.cnt-f.org/spip.php?page=backend',
        'https://cnt69.cnt-f.org/feed/',
        'https://www.confederationpaysanne.fr/sites/1/rss/rss_communiques_de_presse.xml',
        'https://www.fnsea.fr/actualit%C3%A9s/feed/',
        'https://www.force-ouvriere.fr/spip.php?page=backend',
        'https://www.fsdl.fr/feed/',
        'https://fsu.fr/feed/',
        'https://bretagne.fsu.fr/feed/',
        'https://www.agendamilitant.org/rss.xml',
        'https://le-sages.org/flux_RSS_SAGES.xml',
        'https://www.sell.fr/rss.xml',
        'https://www.snes.edu/feed/',
        'https://www.corse.snes.edu/spip.php?page=backend',
        'https://www.snetap-fsu.fr/spip.php?page=backend',
        'https://static.blog4ever.com/2015/01/793181/rss_articles.xml',
        'https://solidaires.org/spip.php?page=backend',
        'https://solidairesinformatique.org/feed/',
        'https://www.stjv.fr/feed/',
        'https://www.diplomatie.gouv.fr/spip.php?page=backend-fd',
        'https://www.diploweb.com/spip.php?page=backend',
        'https://www.bing.com/news/search?q=cybers%C3%A9curit%C3%A9&qft=sortbydate%3d%221%22%2Binterval%3d%227%22&form=YFNR&format=rss&cc=fr',
        'https://www.france24.com/fr/tag/cybers%C3%A9curit%C3%A9/rss',
        'https://www.lemonde.fr/cybercriminalite/rss_full.xml',
        'https://www.itpublic.fr/cybersecurite/feed/',
        'https://incyber.org/categorie/gestion-des-risques/feed/',
        'https://incyber.org/categorie/souverainete-numerique/feed/',
        'https://incyber.org/categorie/secops/feed/'
	'https://stop-croisieres.org/feed/'
    ],
    'en': [
        'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
	'https://www.lloydslist.com/rss-feeds',
	'https://services.tradewindsnews.com/api/feed/rss',
	'https://www.maritime-executive.com/articles.rss',
	'http://rss.cnn.com/rss/edition.rss',
	'https://www.ship-technology.com/feed/',
	'https://www.marinelink.com/feeds',
	'https://www.marinelog.com/feed/',
	'https://www.maritime-executive.com/articles.rss',
	'https://www.freightwaves.com/news/feed',
        'https://feeds.foxnews.com/foxnews/latest',
        'https://feeds.npr.org/1001/rss.xml',
        'https://www.wsj.com/xml/rss/3_7085.xml',
        'https://feeds.bbci.co.uk/news/rss.xml',
        'https://www.theguardian.com/uk/rss',
        'https://rss.telegraph.co.uk/news.xml',
        'https://www.independent.co.uk/news/uk/rss',
        'https://feeds.skynews.com/feeds/rss/uk.xml',
        'https://www.abc.net.au/news/feed/51120/rss.xml',
        'https://www.smh.com.au/rss/feed.xml',
        'https://www.theage.com.au/rss/feed.xml',
        'https://www.news.com.au/rss',
        'https://www.australiangeographic.com.au/rss/',
        'https://www.thestar.com/content/thestar/feed.RSSManagerServlet.news.rss',
        'https://www.ctvnews.ca/rss/TopStories',
        'https://globalnews.ca/feed/',
        'https://www.theglobeandmail.com/incoming/gnml?type=rss'
        'https://abcnews.go.com/abcnews/internationalheadlines',
        'https://feeds.bbci.co.uk/news/world/rss.xml',
        'https://www.cbsnews.com/latest/rss/world',
        'https://www.cnbc.com/id/100727362/device/rss/rss.html',
        'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
        'https://feeds.skynews.com/feeds/rss/world.xml',
        'https://latest-edition.feed.theworld.org/',
        'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
        'https://www.dailymail.co.uk/news/worldnews/index.rss',
        'https://www.globalissues.org/news/feed',
        'https://wtf.roflcopter.fr/rss-bridge/?action=display&bridge=Reuters&feed=world&format=Mrss',
        'https://www.economist.com/international/rss.xml',
        'https://timesofindia.indiatimes.com/rssfeeds/296589292.cms',
        'https://zeenews.india.com/rss/world-news.xml',
        'https://www.standard.co.uk/news/world/rss',
        'https://www.lemonde.fr/en/international/rss_full.xml',
        'https://cdn.feedcontrol.net/8/1115-TvWAhu4G064WT.xml',
        'https://www.theguardian.com/world/rss',
        'https://www.timesunion.com/default/feed/Breaking-News-240.php',
        'https://www.firstpost.com/commonfeeds/v1/mfp/rss/world.xml',
        'https://mondediplo.com/rss/',
        'https://www.rfi.fr/en/international/rss',
        'https://feeds.washingtonpost.com/rss/world',
        'https://www.washingtontimes.com/rss/headlines/news/world/'
    ],
    'es': [
        'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/rss_home',
	'https://sectormaritimo.es/feed',
	'https://www.elvigia.com/feed/',
	'https://www.transportexxi.com/feed/',
	'https://www.abc.es/rss/feeds/abc_ultima.xml',
        'https://e00-elmundo.uecdn.es/elmundo/rss/espana.xml',
        'https://www.lavanguardia.com/mvc/feed/rss/home',
        'https://www.elconfidencial.com/rss/espana.xml',
        'https://www.publico.es/rss/',
        'https://www.larazon.es/rss/',
        'https://www.eldiario.es/rss/',
        'https://www.expansion.com/rss/portada.xml',
        'https://www.marca.com/en/directo/rss.xml',
        'https://as.com/rss/tags/ultimas_noticias.xml',
        'https://www.europapress.es/rss/rss.aspx',
        'https://www.rtve.es/rss/temas_noticias.xml',
        'https://www.cope.es/rss/portada.xml',
        'https://www.20minutos.es/rss/'
        'https://elpais.com/rss/elpais/portada.xml',
        'https://www.abc.es/rss/feeds/abc_ultima.xml',
        'http://www.puertosynavieras.es/rss/rss.xml'
    ],
    'it': [ 
    'https://www.repubblica.it/rss/homepage/rss2.0.xml',
    'https://www.informare.it/imare/rss.htm',
    'https://www.ship2shore.it/rss',
    'https://pre.themeditelegraph.com/it/rss/copertina.xml',
    'https://www.portnews.it/feed/',
    'https://www.corrieremarittimo.it/feed/',
    'https://xml2.corriereobjects.it/rss/homepage.xml',
    'https://www.ansa.it/sito/ansait_rss.xml',
    'https://www.ilsole24ore.com/rss/italia--attualita.xml',
    'https://www.lastampa.it/rss.xml',
    'https://www.ilfattoquotidiano.it/feed/',
    'https://www.ilmessaggero.it/rss/home.xml',
    'https://www.leggo.it/rss/home.xml',
    'https://www.tgcom24.mediaset.it/rss/homepage.xml',
    'https://www.rainews.it/rss/Pages/default.aspx',
    'https://www.ilgiornale.it/feed.xml',
    'https://www.liberoquotidiano.it/rss.xml',
    'https://www.huffingtonpost.it/rss.xml',
    'https://www.adnkronos.com/rss.xml',
    'https://www.iltempo.it/rss.xml'
        'https://www.repubblica.it/rss/homepage/rss2.0.xml',
        'https://www.corriere.it/rss/homepage.xml',
        'http://shippingitaly.it/feed/'
    ],
    'pt': [
    'https://www.publico.pt/rss',
    'https://www.jornaldaeconomiadomar.com/xmlrpc.php?rsd',
    'https://revistademarinha.com/feed/',
    'https://www.jornaldenegocios.pt/rss',
    'https://feeds.dn.pt/DN-Actual',
    'https://expresso.pt/rss/ultimas',
    'https://www.jn.pt/rss/',
    'https://www.cmjornal.pt/rss.aspx',
    'https://www.tsf.pt/rss/tsf.xml',
    'https://www.sabado.pt/rss',
    'https://www.jornaldenegocios.pt/homepage/rss',
    'https://www.ojogo.pt/rss/',
    'https://www.record.pt/rss/',
    'https://www.aeiou.pt/rss',
    'https://www.correiodominho.pt/rss/',
    'https://www.diariodominho.pt/rss/',
    'https://www.avante.pt/rss/',
    'https://www.portugalresident.com/feed/',
    'https://www.theportugalnews.com/rss/',
    'https://eco.sapo.pt/feed/',
    'https://www.noticiasaominuto.com/rss/',
    'https://www.porto24.pt/rss/',
    'https://feeds.sapo.pt/'
    ],
    'de': [
    'https://www.spiegel.de/international/index.rss',
    'https://hansa.podigee.io/feed/mp3',
    'https://www.tagesschau.de/xml/rss2/',
    'https://newsfeed.zeit.de/index',
    'https://www.sueddeutsche.de/app/service/rss/alles/rss.xml',
    'https://www.welt.de/feeds/latest.rss',
    'https://www.handelsblatt.com/contentexport/feed/homepage',
    'https://www.n-tv.de/rss',
    'https://www.dw.com/en/top-stories/s-9097/rss',
    'https://rss.focus.de/fol/xml/rss_folnews.xml',
    'https://www.faz.net/rss/aktuell/',
    'https://www.berliner-zeitung.de/feed/rss',
    'https://www.stern.de/feed/standard/alle-nachrichten/',
    'https://rss.br.de/nachrichten',
    'https://www.zdf.de/rss/zdfheute-100',
    'https://www.mdr.de/nachrichten/rss/news-100.html',
    'https://www.fr.de/rss/rss.xml',
    'https://www.rnd.de/rss-feed',
    'https://www.ksta.de/rss',
    'https://www.lr-online.de/rss',
    'https://www.tagesspiegel.de/contentexport/feed/home'
        'https://www.dw.com/de/rssfeed/topstories',
        'https://www.spiegel.de/schlagzeilen/tops/index.rss',
        'http://www.hansa-online.de/rss'
    ],
    'nl': [
    'https://feeds.nos.nl/nosnieuwsalgemeen',
    'https://www.telegraaf.nl/rss',
    'https://www.volkskrant.nl/nieuws/rss.xml',
    'https://www.ad.nl/binnenland/rss.xml',
    'https://www.parool.nl/rss.xml',
    'https://www.trouw.nl/rss.xml',
    'https://www.nrc.nl/rss/',
    'https://www.nu.nl/rss',
    'https://www.rtlnieuws.nl/rss',
    'https://www.omroepwest.nl/rss',
    'https://www.gelderlander.nl/rss.xml',
    'https://www.rijnmond.nl/rss',
    'https://www.dvhn.nl/rss.xml',
    'https://www.ed.nl/rss.xml',
    'https://www.bd.nl/rss.xml',
    'https://www.destentor.nl/rss.xml',
    'https://www.tubantia.nl/rss.xml',
    'https://www.lc.nl/rss.xml',
    'https://www.frieschdagblad.nl/rss.xml',
    'https://www.brabantsdagblad.nl/rss.xml'
    'https://www.telegraaf.nl/rss',
    'www.schuttevaer.nl/rss'
    ],
    'zh': [
    'http://www.xinhuanet.com/english/rss/china.xml',  # Xinhua - Actualités en anglais
    'http://www.chinadaily.com.cn/rss/topnews.xml',  # China Daily - Actualités générales
    'http://en.people.cn/rss/90882.xml',  # People's Daily - Actualités générales
    'https://www.globaltimes.cn/RSS.xml',  # Global Times - Perspectives chinoises en anglais
    'https://supchina.com/feed/',  # SupChina - Actualités sur la Chine (anglais)
    'https://www.scmp.com/rss/2/feed',  # South China Morning Post - Actualités Hong Kong et Chine (anglais)
    'https://news.cgtn.com/rss/index.xml',  # CGTN - China Global Television Network (anglais)
    'https://chinaplus.cri.cn/english/rss/rss.xml',  # CRI - China Radio International
    'https://ecns.cn/rss/ecns.rss',  # ECNS - China News Service
    'http://www.chinatoday.com.cn/english/rss.xml',  # China Today - Actualités en anglais
    'https://feeds.shanghaidaily.com/rss/latest',  # Shanghai Daily - Actualités locales (anglais)
    'https://www.whatsonweibo.com/feed/',  # What's On Weibo - Culture et médias sociaux chinois (anglais)
    'https://technode.com/feed/',  # TechNode - Technologie et startups en Chine (anglais)
    'https://www.china-briefing.com/news/feed/',  # China Briefing - Actualités économiques et commerciales (anglais)
    'https://www.caixinglobal.com/rss/news.xml',  # Caixin Global - Actualités économiques et politiques (anglais)
    'https://www.chinadaily.com.cn/',
    'http://rss.sina.com.cn/news/china/focus15.xml',
    'http://www.zgsyb.com/rss'
    ],
    'ja': [
    'https://www3.nhk.or.jp/nhkworld/en/news/feeds/rss.xml',  # NHK World - Actualités en anglais
    'https://www.japantimes.co.jp/feed/',  # The Japan Times - Actualités générales (anglais)
    'https://mainichi.jp/rss/etc/flash-enb.xml',  # Mainichi Shimbun - Flash News (anglais)
    'https://www.asahi.com/rss/asahi/newsheadlines.rdf',  # Asahi Shimbun - Actualités générales (japonais)
    'https://www.yomiuri.co.jp/rss/yoltopnews.rdf',  # Yomiuri Shimbun - Top News (japonais)
    'https://feeds.nikkei.com/nikkei/news',  # Nikkei - Actualités économiques (japonais)
    'https://japantoday.com/feed',  # Japan Today - Actualités en anglais
    'https://soranews24.com/feed/',  # SoraNews24 - Culture pop et tendances japonaises (anglais)
    'https://en.rocketnews24.com/feed/',  # RocketNews24 - Nouvelles insolites et culturelles (anglais)
    'https://www.japan-guide.com/rss/',  # Japan Guide - Tourisme et culture (anglais)
    'https://www.animenewsnetwork.com/encyclopedia/reports.xml',  # Anime News Network - Actualités sur l'animation (anglais)
    'https://www.japantvnews.com/rss/',  # Japan TV News - Télévision et actualités (anglais)
    'https://www.japanesepod101.com/podcast/feed.xml',  # JapanesePod101 - Apprentissage de la langue japonaise
    'https://www.nippon.com/rss/en/index.xml',  # Nippon.com - Perspectives japonaises (anglais)
    'https://www.jiji.com/rss/rss_e.rdf',  # Jiji Press - Actualités rapides (anglais)
    'https://www.asahi.com/rss/asahi/newsheadlines.rdf',
    'https://www3.nhk.or.jp/rss/news/cat0.xml',
    'http://kaijipress.com/rss'
    ],
    'ar': [
    'https://www.aljazeera.com/xml/rss/all.xml',  # Al Jazeera - Actualités générales
    'https://www.themaritimestandard.com/feed/',
    'https://www.arabnews.com/rss_main.xml',  # Arab News - Actualités régionales
    'https://www.thenationalnews.com/rss',  # The National - Émirats arabes unis
    'https://aawsat.com/rss',  # Asharq Al-Awsat - Journal panarabe
    'https://www.middleeasteye.net/rss',  # Middle East Eye - Actualités et analyses
    'https://www.gulfnews.com/rss',  # Gulf News - Moyen-Orient (anglais)
    'https://www.zawya.com/rss/en/all.xml',  # Zawya - Actualités économiques et commerciales
    'https://english.alarabiya.net/.mrss/en/home/english.xml',  # Al Arabiya - Économie et actualités (anglais)
    'https://www.khaleejtimes.com/apps/pbcs.dll/section?Category=RSS',  # Khaleej Times - Actualités générales et économiques
    'https://www.middleeastmonitor.com/rss/',  # Middle East Monitor - Société et culture
    'https://www.arabianbusiness.com/rss',  # Arabian Business - Actualités économiques et lifestyle
    'https://www.al-monitor.com/rss',  # Al Monitor - Perspectives sur le Moyen-Orient
    'https://www.memri.org/rss.xml',  # MEMRI - Analyses politiques et culturelles
    'https://www.dailystar.com.lb/rss.aspx',  # The Daily Star - Liban
    'https://www.jordantimes.com/rss/rss.xml',  # The Jordan Times - Jordanie
    'https://www.moroccoworldnews.com/feed/',  # Morocco World News - Maroc (anglais)
    'https://www.tunisia-live.net/feed/',  # Tunisia Live - Tunisie
    'https://www.albawaba.com/rss/news',  # Albawaba - Actualités régionales
    'https://english.ahram.org.eg/rss.aspx',  # Al-Ahram Weekly - Égypte (anglais)
    'https://www.sana.sy/en/?feed=rss2',  # SANA - Agence de presse syrienne (angla
        
    ],
    'he': [
    'https://www.jpost.com/Rss/RssFeedsHeadlines.aspx',  # The Jerusalem Post - Actualités générales
    'https://www.haaretz.com/rss.xml',  # Haaretz - Actualités générales et analyses (anglais)
    'https://www.ynetnews.com/category/3082',  # Ynet News - Actualités générales (anglais)
    'https://rss.walla.co.il/feed/22',  # Walla! News - Actualités générales (hébreu)
    'https://www.timesofisrael.com/feed/',  # The Times of Israel - Actualités et analyses (anglais)
    'https://en.globes.co.il/en/globes-rss-feed.xml',  # Globes - Actualités économiques (anglais)
    'https://www.calcalist.co.il/localRSS.xml',  # Calcalist - Économie et affaires (hébreu)
    'https://www.jpost.com/Business/Rss.xml',  # Jerusalem Post - Économie (anglais)
    'https://rss.themarker.com/',  # The Marker - Actualités économiques (hébreu)
    'https://www.geektime.co.il/rss/',  # Geektime - Technologie et startups (hébreu)
    'https://nocamels.com/feed/',  # NoCamels - Startups et innovation (anglais)
    'https://www.israel21c.org/feed/',  # Israel21c - Innovation et culture (anglais)
    'https://www.debka.com/feed/',  # Debka File - Analyses de sécurité et renseignement (anglais)
    'https://www.i24news.tv/en/rss',  # i24 News - Politique et sécurité (anglais)
    'https://www.jpost.com/Middle-East/Rss.xml',  # Jerusalem Post - Moyen-Orient (anglais)
    'https://www.haaretz.com/culture/.premium.rss',  # Haaretz - Culture (anglais)
    'https://www.timesofisrael.com/topic/culture/feed/',  # Times of Israel - Culture (anglais)
    'https://www.israelhayom.co.il/rss/',  # Israel Hayom - Actualités générales et culture (hébreu)
    'https://www.jewishpress.com/feed/'  # The Jewish Press - Société et perspectives juives (anglais)
    'https://www.ynet.co.il/Integration/StoryRss1854.xml',
    'https://www.haaretz.co.il/cmlink/1.1612072',
    'http://www.port2port.co.il/rss'
    ]
}

# Messages humoristiques pour WhatsApp
humor_messages_whatsapp = [
    "Hey, voici les dernières nouvelles !",
    "Salut, un petit mail avec des articles pour toi !",
    "Yo ! Regarde les articles dans ta boîte mail.",
    "Bonjour ! Check ton email pour un peu de lecture !",
    "Salut, voici des infos intéressantes dans ta boîte mail.",
    "Hello ! Quelques articles récents par email pour toi !",
    "Hey ! Des news fraîches, direction tes emails !",
    "Salut, va voir ton email pour les derniers articles.",
    "Bonjour ! Consulte ton mail pour les nouvelles du jour.",
    "Yo ! Regarde ce qu'il y a dans ton inbox."
]

# Phrases humoristiques pour le corps du texte
humor_sentences_body = [
    "Pourquoi les développeurs aiment-ils les flux RSS ? Parce qu'ils aiment être alimentés en continu !",
    "Coder et lire des news, c'est comme boire un bon café en terrasse... mais sans le café.",
    "Ne vous inquiétez pas, ces articles sont triés sur le volet par un bot qui ne dort jamais.",
    "Les articles d'aujourd'hui ? Plus frais que vos croissants du matin !",
    "Si vous trouvez un bug dans ces articles, dites-vous que c'est pour maintenir votre esprit critique en forme !",
    "Pas besoin de Google, tout ce que vous cherchez est déjà dans votre boîte mail !",
    "Alerte ! Ces articles sont plus addictifs que Netflix.",
    "Un bon article vaut mieux qu'une mauvaise série télé, non ?",
    "N'ayez pas peur de cliquer sur les liens, ils ne mordent pas (je crois).",
    "Un flux RSS par jour éloigne l'ennui pour toujours."
]

# Phrases humoristiques pour les conclusions
humor_sentences_conclusion = [
    "Rappelez-vous : un article par jour éloigne l'ennui toujours !",
    "Et voilà pour aujourd'hui, à demain pour d'autres infos croustillantes !",
    "Si vous avez aimé ces articles, n'hésitez pas à liker... oh, attendez, ce n'est pas Instagram.",
    "N'oubliez pas : savoir, c'est pouvoir, alors lisez ces articles !",
    "Si ces articles vous ennuient, c'est probablement parce que vous êtes trop intelligent.",
    "Et maintenant, une pause café bien méritée après ces lectures !",
    "Merci d'avoir lu jusqu'ici, vous êtes le MVP du jour.",
    "Pensez à partager ces infos, ou gardez-les jalousement pour vous !",
    "Et si vous partagiez ces articles avec quelqu'un d'autre pour faire briller votre culture générale ?",
    "Je parie que vous êtes déjà prêt pour le prochain email !"
]

flags_by_language = {
    'fr': "🇫🇷", 'en': "🇬🇧", 'es': "🇪🇸", 'it': "🇮🇹",
    'de': "🇩🇪", 'nl': "🇳🇱", 'zh': "🇨🇳", 'ja': "🇯🇵",
    'ar': "🇦🇪", 'he': "🇮🇱", 'pt': "🇵🇹"
}

# Assurez-vous d'utiliser une version compatible de googletrans
from googletrans import Translator
translator = Translator()


# ---------------------------
# SECTION 2 : LOGGING ET ARCHIVAGE
# ---------------------------

# Configuration des logs
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Vérification des doublons (liens archivés)
def is_duplicate(link):
    if not os.path.exists(archive_file):
        return False
    with open(archive_file, 'r') as f:
        stored_links = f.read().splitlines()
    # Vérification stricte des doublons par hachage
    hashed_link = hashlib.md5(link.encode('utf-8')).hexdigest()
    return any(hashed_link in line for line in stored_links)

def mark_as_sent(link, lang):
    hashed_link = hashlib.md5(link.encode('utf-8')).hexdigest()
    with open(archive_file, 'a') as f:
        f.write(f"{datetime.now().isoformat()} | {lang} | {hashed_link}\n")

# SECTION 3 : ANALYSE DES FLUX RSS
# ---------------------------

def analyze_feed(rss_feed, lang):
    logging.info(f"Analyse du flux : {rss_feed}")
    
    # Analyse du flux RSS
    feed = feedparser.parse(rss_feed)
    
    if not feed.entries:
        logging.warning(f"Flux vide ou invalide : {rss_feed}")
        return []  # Si aucun article, retour vide

    found_articles = []
    seen_titles = set()  # Pour éviter les doublons d'articles
    max_date_threshold = datetime.now() - timedelta(days=MAX_ARTICLE_AGE_DAYS)

    for entry in feed.entries:
        # Vérifier que les champs essentiels existent
        if not hasattr(entry, 'title') or not hasattr(entry, 'link'):
            logging.warning(f"Article sans titre ou lien ignoré : {entry}")
            continue
        
        if entry.title in seen_titles:  # Éviter les doublons
            continue
        seen_titles.add(entry.title)

        if is_duplicate(entry.link):  # Vérifie si l'article a déjà été envoyé
            continue

        # Vérifie la date de l'article
        try:
            if hasattr(entry, 'published_parsed') and entry.published_parsed:
                article_date = datetime(*entry.published_parsed[:6])
                if article_date < max_date_threshold:
                    continue
            else:
                # Ajouter une date par défaut si aucune date n'est trouvée
                article_date = datetime.now()
                logging.warning(f"Aucune date trouvée pour l'article : {entry.title}. Date par défaut attribuée.")
        except Exception as e:
            logging.warning(f"Erreur de traitement de la date : {e}")
            continue

        # Analyse des mots-clés dans le titre, le résumé et le contenu complet
        content = ''
        if hasattr(entry, 'content') and entry.content:
            content = ' '.join([c.get('value', '') for c in entry.content if isinstance(c, dict)])
        elif hasattr(entry, 'summary'):
            content = entry.summary  # Utiliser le résumé si le contenu n'est pas disponible

        # Recherche des mots-clés
        keywords_found = [
            kw for kw in keywords_by_language.get(lang, [])
            if (kw.lower() in entry.title.lower() or  # Cherche dans le titre
                kw.lower() in content.lower())  # Cherche dans le contenu ou le résumé
        ]

        if keywords_found:  # Si des mots-clés sont trouvés
            try:
                translated_title = translator.translate(entry.title, dest='fr').text
                found_articles.append({
                    "title": entry.title,
                    "translated_title": translated_title,
                    "link": entry.link,
                    "flag": flags_by_language.get(lang, "🌍"),
                    "keywords": keywords_found
                })
                mark_as_sent(entry.link, lang)  # Marquer l'article comme envoyé
            except Exception as e:
                logging.warning(f"Erreur lors de la traduction ou de l'ajout de l'article : {e}")

    return found_articles
# ---------------------------
# SECTION 4 : ENVOI DES EMAILS ET WHATSAPP
# ---------------------------

def send_email(subject, articles, summary):
    msg = MIMEMultipart()
    msg['From'] = from_email
    msg['To'] = ", ".join(to_emails)
    msg['Subject'] = subject

    # Contenu humoristique (début et conclusion)
    humor_body = random.choice(humor_sentences_body)
    humor_conclusion = random.choice(humor_sentences_conclusion)

    # Construire le corps de l'email
    body_content = f"""
    {humor_body}<br><br>
    {summary}  <!-- Résumé statistique ajouté ici -->
    <br><br><h2>Articles récents</h2><ul>
    """

    # Ajouter les articles au corps de l'e-mail
    for article in articles:
        keywords_str = ', '.join(f"<span style='color:red; font-weight:bold;'>{kw}</span>" for kw in article["keywords"])
        body_content += f"""
            <li>{article['flag']} <b>{article['translated_title']}</b> : 
            {keywords_str} - <a href="{article['link']}">[Lire]</a></li>
        """
    body_content += "</ul><br><br>"

    # Ajouter la conclusion humoristique
    body_content += f"{humor_conclusion}<br><br>"

    # Ajouter le logo en signature (s'il existe)
    if os.path.exists(logo_path):
        with open(logo_path, 'rb') as f:
            logo = MIMEImage(f.read())
            logo.add_header('Content-ID', '<logo>')
            logo.add_header('Content-Disposition', 'inline', filename=os.path.basename(logo_path))
            msg.attach(logo)
        body_content += '<br><br><img src="cid:logo" alt="Logo">'
    else:
        logging.warning("Logo non trouvé. Aucun logo ajouté dans l'e-mail.")

    # Ajouter le contenu HTML final
    msg.attach(MIMEText(body_content, 'html'))

    # Envoi de l'email via SMTP
    try:
        logging.info("Connexion au serveur SMTP...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(from_email, password)
        logging.info("Envoi de l'email...")
        server.sendmail(from_email, to_emails, msg.as_string())
        server.quit()
        logging.info("Email envoyé avec succès.")
    except smtplib.SMTPAuthenticationError as e:
        logging.error(f"Erreur d'authentification SMTP : {e}")
    except smtplib.SMTPException as e:
        logging.error(f"Erreur SMTP : {e}")
    except Exception as e:
        logging.error(f"Erreur générale lors de l'envoi : {e}")

# ---------------------------
# SECTION 5 : PLANIFICATION
# ---------------------------

import schedule
import time
import logging

def send_whatsapp_message(phone_number):
    message = random.choice(humor_messages_whatsapp)
    try:
        sendwhatmsg_instantly(phone_number, message)
        logging.info(f"Message WhatsApp envoyé à {phone_number}")
    except Exception as e:
        logging.error(f"Erreur d'envoi WhatsApp : {e}")

# Fonction principale qui réalise les tâches nécessaires
def job():
    logging.info("Début de la recherche.")
    all_articles = []  # Liste pour collecter les articles
    stats = {
        'total_analyzed': 0,  # Total des articles analysés
        'filtered': 0,        # Articles retenus après filtrage
        'by_language': {}     # Articles filtrés par langue
    }

    # Analyse des flux RSS pour chaque langue
    for lang, feeds in rss_feeds.items():
        stats['by_language'][lang] = 0  # Initialiser le compteur par langue
        for rss_feed in feeds:
            try:
                articles = analyze_feed(rss_feed, lang)
                stats['total_analyzed'] += len(feedparser.parse(rss_feed).entries)  # Articles analysés
                stats['filtered'] += len(articles)  # Articles filtrés
                stats['by_language'][lang] += len(articles)  # Articles filtrés par langue
                if articles:
                    all_articles.extend(articles)
            except Exception as e:
                logging.error(f"Erreur avec le flux {rss_feed} : {e}")

    # Construire un résumé statistique pour l'e-mail
    summary = f"""
    <h2>Résumé du jour</h2>
    <p><b>Total d'articles analysés :</b> {stats['total_analyzed']}</p>
    <p><b>Articles retenus après filtrage :</b> {stats['filtered']}</p>
    <h3>Répartition par langue :</h3>
    <ul>
    """
    for lang, count in stats['by_language'].items():
        summary += f"<li>{flags_by_language.get(lang, '🌍')} {lang.upper()} : {count} articles</li>"
    summary += "</ul>"

    # Envoi des e-mails si des articles sont disponibles
    if all_articles:
        send_email("Rapport quotidien", all_articles, summary)

    # Envoi des messages WhatsApp
    for number in whatsapp_numbers:
        try:
            send_whatsapp_message(number)
            logging.info(f"Message WhatsApp envoyé à {number}")
        except Exception as e:
            logging.error(f"Erreur d'envoi WhatsApp à {number} : {e}")


# Fonction pour envoyer les e-mails (inchangée mais adaptée pour ton message personnalisé)
def send_email(subject, articles, summary):
    msg = MIMEMultipart()
    msg['From'] = from_email
    msg['To'] = from_email  # Affiche uniquement l'expéditeur ou un alias
    msg['Subject'] = subject

    # Ajoutez les destinataires dans le champ Bcc
    bcc_emails = to_emails  # Utilisation de la liste des destinataires

    # Contenu humoristique (début et conclusion)
    humor_body = random.choice(humor_sentences_body)
    humor_conclusion = random.choice(humor_sentences_conclusion)

    # Ton message humoristique préféré
    personalized_message = """
    <i>
    Salut les aventuriers de l’info maritime ! 🚢
    Chaque jour, votre boîte mail devient une véritable mine d’or d’articles triés sur le volet. 
    Grâce à des mots-clés bien aiguisés et des flux RSS aux quatre coins du globe, on vous sert sur un plateau 
    les infos les plus croustillantes sur la sûreté maritime, les ports, et tout ce qui flotte (ou coule, mais on préfère éviter ça) mais pas que!.<br><br>
    👉 Vous avez une idée brillante, un mot-clé qui déchire, ou un flux RSS qui mérite d’être dans la cour des grands ? 
    Balancez-moi vos trouvailles en répondant à cet e-mail ! 
    Merci de faire de votre inbox un endroit où l'ennui ne jette jamais l'ancre ! 🌊
    </i>
    """

    # Construire le corps de l'email
    body_content = f"""
    {humor_body}<br><br>
    {summary}  <!-- Résumé statistique ajouté ici -->
    <br><br><h2>Articles récents</h2><ul>
    """

    # Ajouter les articles au corps de l'e-mail
    for article in articles:
        keywords_str = ', '.join(f"<span style='color:red; font-weight:bold;'>{kw}</span>" for kw in article["keywords"])
        body_content += f"""
            <li>{article['flag']} <b>{article['translated_title']}</b> : 
            {keywords_str} - <a href="{article['link']}">[Lire]</a></li>
        """
    body_content += "</ul><br><br>"

    # Ajouter la conclusion humoristique
    body_content += f"{humor_conclusion}<br><br>"

    # Ajouter ton message humoristique en italique avant le logo
    body_content += f"{personalized_message}<br><br>"

    # Ajouter le logo en signature (s'il existe)
    if os.path.exists(logo_path):
        with open(logo_path, 'rb') as f:
            logo = MIMEImage(f.read())
            logo.add_header('Content-ID', '<logo>')
            logo.add_header('Content-Disposition', 'inline', filename=os.path.basename(logo_path))
            msg.attach(logo)
        body_content += '<br><br><img src="cid:logo" alt="Logo">'
    else:
        logging.warning("Logo non trouvé. Aucun logo ajouté dans l'e-mail.")

    # Ajouter le contenu HTML final
    msg.attach(MIMEText(body_content, 'html'))

    # Envoi de l'email via SMTP
    try:
        logging.info("Connexion au serveur SMTP...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(from_email, password)
        logging.info("Envoi de l'email...")
        server.sendmail(from_email, bcc_emails, msg.as_string())
        server.quit()
        logging.info("Email envoyé avec succès.")
    except smtplib.SMTPException as e:
        logging.error(f"Erreur SMTP : {e}")


# Planification de l'exécution de la tâche toutes les 6 heures
schedule.every(6).hours.do(job)

if __name__ == "__main__":
    job()  # Exécution immédiate
    while True:
        schedule.run_pending()  # Vérifie si une tâche planifiée doit être exécutée
        time.sleep(1)  # Pause pour éviter de surcharger le CPU

# ---------------------------
# POINT D'ENTRÉE DU SCRIPT
# ---------------------------
if __name__ == "__main__":
    job()  # Lancement d'une seule analyse et envoi


